CREATE TABLE `GuitarScorePic` (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  uid VARCHAR(19) NOT NULL,
  score_uid VARCHAR(19) NOT NULL,
  url VARCHAR(256) NOT NULL,
  created_at DATETIME NOT NULL
)